url: "https://iota-school.github.io/nonvisual_data_science_workshops/" # the base hostname & protocol for your site, e.g. http://example.com
root: /
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Nonvisual Data Science Workshops Series"


collections:
collections:
  projects:
    output: true
    order:
     - stsci.md
